### ISSUE TITLE
Can not limit the height of react-calendar-timeline parent <div>

### ISSUE THREAD

**Issue by besteric** [namespace-ee/react-calendar-timeline#146]
![can](https://user-images.githubusercontent.com/535385/28652077-1c02cfc6-72b8-11e7-81dc-d74284870d75.gif)

i want limit the calendar into a fixation height box，so i add some css to the react-calendar-timeline parent div

```css
.demo-demo {
    margin-top: 35px;
    height: 500px;
    overflow: scroll;
}
```

the item drag event looks like will not work correct
