### ISSUE TITLE
Browser Zoom causes row height mismatch problem

### ISSUE THREAD

**Issue by devictokai** [namespace-ee/react-calendar-timeline#265]
Looking at the test case at [codesandbox.io](https://codesandbox.io/s/qlj6qvjrnw) , with Chrome or Firexfox with the browsers zoom level set to 100%, the table looks fine.

However when changing the zoom level to 110% in Chrome, the row height of the calendar item titles on the left, no longer matches the row height of the calendar items on the right. Can be seen if looking at the last row at bottom of the table in the linked codesandbox.

![image](https://user-images.githubusercontent.com/38119362/38398904-f8525e0c-3981-11e8-956e-472afa9e134b.png)

For Firefox, the misalignment becomes increasingly worse with increased zoom level.

![image](https://user-images.githubusercontent.com/38119362/38398935-25b33b32-3982-11e8-8c2d-6432edac6f87.png)

Additionally, the bug also seems to occur on some machines with high dpi displays, even with the zoom level set to 100%.  (Whereas, another zoom level, such as 130%, might work)

**Comment by devictokai** [comment]
As a FYI, one of our developers is currently using the following css snippet as a workaround.
I thought I'd add it here as a hint to in what area the problem might be in.

```css
/* for browser zoom bug, search item part */
.react-calendar-timeline .rct-sidebar .rct-sidebar-row {
   border-bottom-width: 0 !important;
   padding-bottom: 1px !important;
}
.react-calendar-timeline .rct-sidebar .rct-sidebar-row .rct-sidebar-row-odd {
   border-bottom-width: 0 !important;
   padding-bottom: 1px !important;
}
/* for browser zoom bug, calender part */
.react-calendar-timeline .rct-horizontal-lines .rct-hl-odd {
   border-bottom-color: #f2f2f2 !important; }
.react-calendar-timeline .rct-horizontal-lines .rct-hl-even, .react-calendar-timeline.rct-horizontal-lines .rct-hl-odd {
  border-bottom-color: white;
 }
```
